### PR TITLE
Fix language detection

### PR DESCRIPTION
**Pull request by DecimalTurn**
This PR fixes languages detection issues in the repo which is currently detected as a VB6 repo.

image

This PR only edits lines at the top of files to make sure that GitHub-Linguist detects the language properly (Adding missing VB_Name attributes + language comment annotation).

I did use an [automated action](https://github.com/marketplace/actions/add-basic-language-annotation), but I removed it once the job was done.

Once those changes are merged, the repo should be detected as 100% VBA just like my [fork](https://github.com/DecimalTurn/JustMoreVBA) is currently.

image

### CODE REVIEW

**Review by KallunWillock — APPROVED** [review]
Sorry for the delay in responding. Agree completely. Many thanks.

**Comment by DecimalTurn** [comment]
Oh no worries. I see that you've made the change on your side and that's fine too.
It seems only 4 files still have improper heading:
- `ClassModules/VBSJSON.cls` has no header
- `Userforms/frmUserform_Icon.frm` has `Version 5#` instead of `Version 5.00`
- `Userforms/modUserForm_KeyRoutines.bas` has no header
- `Userforms/modUserForm_Shapes.bas` has no header

**Comment by KallunWillock** [comment]
> Oh no worries. I see that you've made the change on your side and that's fine too. It seems only 4 files still have improper heading:
> 
> * `ClassModules/VBSJSON.cls` has no header
> * `Userforms/frmUserform_Icon.frm` has `Version 5#` instead of `Version 5.00`
> * `Userforms/modUserForm_KeyRoutines.bas` has no header
> * `Userforms/modUserForm_Shapes.bas` has no header

Thank you for this. I left those ones alone because I'm half minded to get rid of them for varying reasons. I'm surprised that the header for the UserForm is wrong (you're right, it is wrong) - I should've picked that.

**Comment by DecimalTurn** [comment]
Looks good

**Pull request closed without merging**
